modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/gizmo-ds/abelia-mod/issues"
license = "EPL-2.0"

[[mods]]
modId = "abelia"
version = "${version}"
displayName = "Abelia"
authors = "Gizmo"
description = '''
Abelia Lib
'''
logoFile = "abelia-logo.png"
displayURL = "https://github.com/gizmo-ds/abelia-mod"

[[dependencies.abelia]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abelia]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abelia]]
modId = "cloth_config"
mandatory = false
versionRange = "[11.,)"
ordering = "NONE"
side = "CLIENT"
