modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/gizmo-ds/abelia-mod/issues"
license = "EPL-2.0"

[[mods]]
modId = "abelia"
version = "${version}"
displayName = "Abelia"
displayURL = "https://github.com/gizmo-ds/abelia-mod"
authors = "Gizmo"
description = '''
Abelia Lib
'''
logoFile = "abelia-logo.png"

[[dependencies.abelia]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abelia]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.abelia]]
modId = "cloth_config"
type = "optional"
versionRange = "[15.0.130,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "abelia.mixins.json"

[[mixins]]
config = "abelia-common.mixins.json"
